import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.39.3";
import { decode } from "https://deno.land/std@0.168.0/encoding/base64.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { vehicleType, paintColor, hasBullbar, hasBeacons, hasLightBar, hasXenon, hasSpoiler, hasRunningBoard, hasVisor, wheelType } = await req.json();

    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) throw new Error("LOVABLE_API_KEY is not configured");

    const vehicleNames: Record<string, string> = {
      car: "a modern European sedan car (like a Peugeot 308 or Renault Megane)",
      truck: "a heavy-duty European box truck (like a Renault D-Series or DAF LF)",
      articulated: "a European articulated semi-truck with trailer (like a Renault T-Series or Scania R-Series)"
    };

    const vehicleName = vehicleNames[vehicleType] || vehicleNames.car;
    
    const colorDescriptions: Record<string, string> = {
      '#ffffff': 'white',
      '#ff0000': 'bright red',
      '#0000ff': 'royal blue',
      '#ffd700': 'metallic gold',
      '#000000': 'glossy black',
      '#00ff00': 'lime green',
      '#ff8800': 'orange',
      '#888888': 'silver grey',
      '#c0c0c0': 'silver metallic',
      '#9900ff': 'cosmic purple',
      '#1a1a1a': 'matte black',
      '#cc0033': 'candy red',
    };
    
    const colorDesc = colorDescriptions[paintColor?.toLowerCase()] || `painted in the color ${paintColor}`;

    const accessories: string[] = [];
    if (hasBullbar) accessories.push("a front bull bar / brush guard");
    if (hasBeacons) accessories.push("amber rotating beacons on the roof");
    if (hasLightBar) accessories.push("an LED light bar on top");
    if (hasXenon) accessories.push("bright xenon headlights");
    if (hasSpoiler) accessories.push("a rear spoiler");
    if (hasRunningBoard) accessories.push("side running boards / step bars");
    if (hasVisor) accessories.push("a sun visor above the windshield");
    if (wheelType === 'chrome') accessories.push("shiny chrome alloy wheels");

    const accessoryText = accessories.length > 0 
      ? `The vehicle is equipped with: ${accessories.join(", ")}.` 
      : "";

    const prompt = `Generate a photorealistic studio photograph of ${vehicleName}, ${colorDesc} paint finish, shot from a 3/4 front angle. The vehicle is on a clean dark studio background with dramatic lighting. ${accessoryText} Ultra-detailed, professional automotive photography style, high resolution, sharp focus. No text, no watermarks, no logos.`;

    console.log("Generating vehicle with Lovable AI Gateway, prompt:", prompt.substring(0, 100) + "...");

    // Call Lovable AI Gateway with image generation model
    const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash-image",
        messages: [
          { role: "user", content: prompt }
        ],
        modalities: ["image", "text"],
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error("Lovable AI Gateway error:", response.status, errorText);
      throw new Error(`AI Gateway error: ${response.status} - ${errorText}`);
    }

    const data = await response.json();
    console.log("AI Gateway response received, checking for images...");

    const imageUrl = data.choices?.[0]?.message?.images?.[0]?.image_url?.url;

    if (!imageUrl) {
      console.error("No image in AI response:", JSON.stringify(data).substring(0, 500));
      throw new Error("No image generated by AI model");
    }

    // Extract base64 data from data URL
    const base64Match = imageUrl.match(/^data:([^;]+);base64,(.+)$/);
    if (!base64Match) {
      // If it's already a URL, return it directly
      console.log("Image is a direct URL, returning as-is");
      return new Response(JSON.stringify({ imageUrl }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const mimeType = base64Match[1];
    const imageBase64 = base64Match[2];

    // Upload to Supabase Storage
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    const ext = mimeType === "image/jpeg" ? "jpg" : "png";
    const fileName = `vehicle_${Date.now()}_${Math.random().toString(36).substring(2, 8)}.${ext}`;
    
    const imageBytes = decode(imageBase64);
    
    const { error: uploadError } = await supabase.storage
      .from('vehicle-images')
      .upload(fileName, imageBytes, {
        contentType: mimeType,
        upsert: false,
      });

    if (uploadError) {
      console.error("Storage upload error:", uploadError);
      // Fallback: return base64 data URL directly
      return new Response(JSON.stringify({ imageUrl }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const { data: publicUrlData } = supabase.storage
      .from('vehicle-images')
      .getPublicUrl(fileName);

    const publicUrl = publicUrlData.publicUrl;
    console.log("Vehicle image uploaded successfully:", fileName);

    return new Response(JSON.stringify({ imageUrl: publicUrl }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });

  } catch (e) {
    console.error("generate-vehicle error:", e);
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : "Unknown error" }), {
      status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
